// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ztBbA3K87O01wKMM7KGG4qXfgthWaas',
    appId: '1:115967955508:web:5838669cabd5a3b8e0b061',
    messagingSenderId: '115967955508',
    projectId: 'negos-d2557',
    authDomain: 'negos-d2557.firebaseapp.com',
    storageBucket: 'negos-d2557.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOpLE51utehM2CmJRJ5v60X_Y4PgSrSBE',
    appId: '1:115967955508:android:325567325706c127e0b061',
    messagingSenderId: '115967955508',
    projectId: 'negos-d2557',
    storageBucket: 'negos-d2557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK0NmoWvm61-6tATLTf2tEolWvNIyLPF0',
    appId: '1:115967955508:ios:14c424fa7166e05ce0b061',
    messagingSenderId: '115967955508',
    projectId: 'negos-d2557',
    storageBucket: 'negos-d2557.firebasestorage.app',
    iosBundleId: 'com.example.negos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK0NmoWvm61-6tATLTf2tEolWvNIyLPF0',
    appId: '1:115967955508:ios:14c424fa7166e05ce0b061',
    messagingSenderId: '115967955508',
    projectId: 'negos-d2557',
    storageBucket: 'negos-d2557.firebasestorage.app',
    iosBundleId: 'com.example.negos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4ztBbA3K87O01wKMM7KGG4qXfgthWaas',
    appId: '1:115967955508:web:ce240a999998c32ce0b061',
    messagingSenderId: '115967955508',
    projectId: 'negos-d2557',
    authDomain: 'negos-d2557.firebaseapp.com',
    storageBucket: 'negos-d2557.firebasestorage.app',
  );
}
